name: CI

on: [push]


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Install
      run: |
        pip install -e .
        pip install -r requirements-dev.txt

    - name: Test
      run: |
        pytest -n auto -m 'not slow or slow'

